[package]
name = "sealantern"
version.workspace = true
description = "Minecraft Server Manager"
authors = ["FPS_Z"]
edition.workspace = true
default-run = "sealantern"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.9", features = ["macos-private-api", "protocol-asset", "tray-icon"] }
tauri-plugin-dialog = "2.6"
tauri-plugin-fs = "2.4"
tauri-plugin-http = "2.5"
tauri-plugin-opener = "2.5"
tauri-plugin-process = "2.3"
tauri-plugin-window-state = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sealantern-feature = { path = "../crates/feature" }
sealantern-core = { path = "../crates/core" }
sealantern-infra = { path = "../crates/infra" }
sealantern-application = { path = "../application" }
sealantern-contract = { path = "../crates/contract" }
async-trait = "0.1.91"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.53.1", features = ["sync", "rt", "time"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_System_Registry"] }
