name: 优化请求
description: 请求优化现有功能或体验
title: "[Perf] "
labels: ["performance", "pending"]
body:
  - type: textarea
    id: content
    attributes:
      label: 内容描述
      description: 请说明需要优化的内容
      placeholder: 在这里描述需要优化的内容
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 理由
      description: 请说明需要优化的原因
      placeholder: 在这里填写理由
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: 影响
      description: 可选，请说明优化可能产生的影响
      placeholder: 在这里填写影响
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准
      description: 可选，请说明优化的验收标准
      placeholder: 在这里填写验收标准
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 附加内容
      description: 可选，例如界面草图等补充材料
      placeholder: 在这里填写附加内容
    validations:
      required: false
